### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by dominikberse**

### CODE REVIEW

**Comment by Minims** [comment]
Hello, Is this branch is ready to test or you still have work to make on it ?

**Comment by dominikberse** [comment]
> Hello, Is this branch is ready to test or you still have work to make on it ?

I am testing it myself at the moment, found a few minor mistakes by now but it should be ready for testing soon.

**Comment by dominikberse** [comment]
@Minims So it basically works for me, I had to tweak some things after my last setup from a clean image, but it should be running now. I will give it a final try and see if everything works out of the box for me now, but that will take 1:30h to complete.

If you want, try it for yourself, maybe you can give me some feedback as well (make sure you follow the README in this branch). Good luck!

**Comment by Minims** [comment]
I will give it a try. For now I still some issue like bad-pdu, I want to test with the docker version. Thx. I have 2 blue Mesh light with OOB null

**Comment by Minims** [comment]
@dominikberse It seems working but have some issues : 

Readme : 

List command is not good : 

```
python3 gateway.py list => python3 gateway.py prov list
```

I have also make a PR to use username/password on MQTT : https://github.com/dominikberse/homeassistant-bluetooth-mesh/pull/3 

So Now i can ON/OFF my light. 
But dimming and color change (warm-white) does not do anything. But the control are available in HA.

**Comment by dominikberse** [comment]
Good catch there.

Alright, at least that is working for you now. Not sure about the color change and dimming, though. Could you check the commands that Home Assistant is sending over MQTT or try to adjust the brightness manually over MQTT?

**Comment by Minims** [comment]
@dominikberse

For color change it seems working, but not all the time, need to dig a bit. Maybe its a value min/max issue.

About Dimming,  I need to add this here to make it work: 
https://github.com/dominikberse/homeassistant-bluetooth-mesh/blob/master/gateway/mesh/nodes/light.py#L95

```
        lightness = lightness * 1000
```
 It is not the good solution, because home assistant get a value of 3000% for example.

Is there a way to get dimming & color min/max value from BLE device while provisioning and setup the entity with this ? 

Thanks again, I finally have a hope to integrate my BLE Mesh light :-)

**Comment by dominikberse** [comment]
@Minims Nice, finally some progress :+1: 

I made this a new issue, if I remember correctly I had the color space working for my devices and that is where I  stopped. I am not sure if the devices expose these settings and If I am able to retrieve them, but otherwise a setting in the `config.yaml` would do for now.

**Pull request merged**
